---
apiVersion: v1
kind: Namespace
metadata:
  name: student-api

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: student-api
data:
  DB_URL: postgres://user:password@db-service:5432/studentdb?sslmode=disable

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-api
      component: api
  template:
    metadata:
      labels:
        app: student-api
        component: api
    spec:
      containers:
      - name: api
        image: ghcr.io/dileepkushwaha/sre-bootcamp:1.0.11
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-replica-deployment
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-api
      component: api-replica
  template:
    metadata:
      labels:
        app: student-api
        component: api-replica
    spec:
      containers:
      - name: api-replica
        image: ghcr.io/dileepkushwaha/sre-bootcamp:1.0.11
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: student-api
spec:
  selector:
    app: student-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
