---
apiVersion: v1
kind: Namespace
metadata:
  name: student-api

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: student-api
type: Opaque
data:
  POSTGRES_USER: dXNlcg==   # base64 encoded value for 'user'
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # base64 encoded value for 'password'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-db
  template:
    metadata:
      labels:
        app: student-db
    spec:
      containers:
      - name: db
        image: postgres:latest
        envFrom:
        - secretRef:
            name: db-secrets
        env:
        - name: POSTGRES_DB
          value: studentdb
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: student-api
spec:
  selector:
    app: student-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432