version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - sre_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sre-bootcamp-api
    environment:
      DB_URL: postgres://user:password@db:5432/mydb?sslmode=disable
    depends_on:
      - db
    networks:
      - sre_network
    expose:
      - "8080"

  api_replica:
    image: ghcr.io/dileepkushwaha/sre-bootcamp:1.0.0
    container_name: sre-bootcamp-replica
    environment:
      DB_URL: postgres://user:password@db:5432/mydb?sslmode=disable
    depends_on:
      - db
    networks:
      - sre_network
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    container_name: sre-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - api_replica
    networks:
      - sre_network
    restart: always

volumes:
  db_data:

networks:
  sre_network:
