version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sre-bootcamp
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: postgres://user:password@db:5432/mydb

volumes:
  db_data:

