# externalsecret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: student-api-secrets
  namespace: student-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: student-api-db-secrets
    creationPolicy: Owner
  data:
  - secretKey: DB_URL
    remoteRef:
      key: student-api
      property: DB_URL
  - secretKey: POSTGRES_USER
    remoteRef:
      key: student-api
      property: POSTGRES_USER
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: student-api
      property: POSTGRES_PASSWORD