apiVersion: batch/v1
kind: Job
metadata:
  name: test-run-migrations
  namespace: student-api
spec:
  template:
    spec:
      containers:
      - name: test-migrations
        image: ghcr.io/dileepkushwaha/sre-bootcamp:1.0.1
        command: ["/bin/sh", "-c", "ls -al /root/ && /root/run-migrations.sh"]
      restartPolicy: OnFailure
