{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        {{- toYaml .Values.grafana.nodeSelector | nindent 8 }}
      containers:
      - name: grafana
        image: grafana/grafana:8.3.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.grafana.service.type }}  # Use the service type from values.yaml
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: {{ .Values.grafana.service.nodePort }}  # Use the NodePort from values.yaml
{{- end }}
