{{- if .Values.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      nodeSelector:
        {{- toYaml .Values.prometheus.nodeSelector | nindent 8 }}
      containers:
      - name: prometheus
        image: prom/prometheus:v2.30.3
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.prometheus.service.type }}  # Use the service type from values.yaml
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: {{ .Values.prometheus.service.nodePort }}  # Use the NodePort from values.yaml
{{- end }}
