apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
data:
  DB_URL: postgres://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Release.Name }}-db-service:5432/{{ .Values.database.dbName }}?sslmode=disable

  