apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.database.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc }}