namespace: observability

prometheus:
  enabled: true
  service:
    type: NodePort
    nodePort: 30500
  nodeSelector:
    type: dependent_services

loki:
  enabled: true
  service:
    type: NodePort
    nodePort: 30400
  nodeSelector:
    type: dependent_services

grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30300
  nodeSelector:
    type: dependent_services
  datasources:
    datasources:  # Removed the `yaml` level and placed the structure directly under `datasources`
      - name: Prometheus
        type: prometheus
        url: http://localhost:30500
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://localhost:30400
        access: proxy

promtail:
  config:
    serverPort: 3101
    clients:
      - url: http://localhost:30400/loki/api/v1/push
    scrapeConfigs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: __host__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            replacement: $1
            separator: /
            source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_name]
            target_label: job
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - action: replace
            source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
            target_label: __path__

postgresExporter:
  enabled: true
  env:
    - name: DATA_SOURCE_NAME
      value: "postgresql://user:password@postgresql:5432/studentdb?sslmode=disable"

blackboxExporter:
  enabled: true
  config:
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: []
          method: GET

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
