name: CI Pipeline

on:
  push:
    paths:
      - '**/*.go' # Trigger on any Go files in the repository
      - 'Dockerfile' # Trigger on changes to the Dockerfile
      - '.github/workflows/**' # Trigger on changes to the workflow files
      - 'Makefile' # Trigger on changes to the Makefile
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod download

      - name: Build API
        run: make build-api

      - name: Run tests
        run: make test

      - name: Perform code linting
        run: make lint

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io # Change to 'docker.io' for DockerHub
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: make build-api

      - name: Push Docker image
        run: |
          docker tag sre-bootcamp:1.0.0 ghcr.io/${{ github.repository_owner }}/sre-bootcamp:1.0.0
          docker push ghcr.io/${{ github.repository_owner }}/sre-bootcamp:1.0.0

